version: 2.1

orbs:
  nx: nrwl/nx@1.4.0

jobs:
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - run:
          name: Set dynamic nx run variable
          command: |
            echo "export NX_RUN_GROUP=\"run-group-$CIRCLE_WORKFLOW_ID\";" >> $BASH_ENV
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - run:
          name: Start the agent << parameters.ordinal >>
          command: pnpm exec nx-cloud start-agent
          no_output_timeout: 60m
  main:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - run:
          name: Set dynamic nx run variable
          command: |
            echo "export NX_RUN_GROUP=\"run-group-$CIRCLE_WORKFLOW_ID\";" >> $BASH_ENV
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - nx/set-shas:
          main-branch-name: 'main'
      - run:
          name: Initialize the Nx Cloud distributed CI run
          command: pnpm exec nx-cloud start-ci-run
      - run:
          name: Run workspace lint
          command: pnpm exec nx workspace-lint
      - run:
          name: Check format
          command: pnpm exec nx format:check
      - run:
          name: Run lint
          command: pnpm exec nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
      - run:
          name: Run test
          command: pnpm exec nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage
      - run:
          name: Run build
          command: pnpm exec nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
      - run:
          name: Stop all agents
          command: pnpm exec nx-cloud stop-all-agents
          when: always

workflows:
  version: 2

  build:
    jobs:
      - agent:
          name: Agent << matrix.ordinal >>
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main:
          name: Nx Cloud Main
