name: moje-ime

on:
  workflow_dispatch:
    inputs:
  # push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_DISTRIBUTED_EXECUTION: true
      NX_BRANCH: ${{ github.event.number || github.ref_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'main'
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Initialize the Nx Cloud distributed CI run
        run: npx nx-cloud start-ci-run
      - name: Run lint
        run: npx nx affected --target=lint --parallel=3
      - name: Run build
        run: npx nx affected --target=build --parallel=3
      - name: Run test
        run: npx nx affected --target=test --parallel=3
      - name: Stop all running agents for this CI run
        if: ${{ always() }}
        run: npx nx-cloud stop-all-agents

  agents:
    runs-on: ubuntu-latest
    name: Agent ${{ matrix.agent }}
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
